# Generated by Django 3.2 on 2021-04-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0002_auto_20210407_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery',
            name='images',
        ),
        migrations.AddField(
            model_name='galery',
            name='images',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='imagine.image'),
            preserve_default=False,
        ),
    ]
