# Generated by Django 3.2 on 2021-04-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0003_auto_20210407_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galery',
            new_name='Gallery',
        ),
    ]
