# Generated by Django 3.2 on 2021-04-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0006_auto_20210407_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-pk']},
        ),
    ]
